name: Atualizar EPG a cada 10 minutos

on:
  schedule:
    - cron: '*/5 * * * *'  # a cada 5 minutos
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Baixar múltiplos arquivos epg.xml
        run: |
          curl -L -o epg_limaalef.xml "https://raw.githubusercontent.com/limaalef/BrazilTVEPG/refs/heads/main/epg.xml"
          curl -L -o epg_outro.xml "https://raw.githubusercontent.com/limaalef/BrazilTVEPG/refs/heads/main/claro.xml"

      - name: Commit e push (se houver mudanças)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add epg_limaalef.xml epg_outro.xml
          if git diff --cached --quiet; then
            echo "Nenhuma mudança detectada"
          else
            git commit -m "Atualização automática dos arquivos EPG"
            git push
          fi
