name: Atualizar EPG a cada 10 minutos

on:
  schedule:
    - cron: '*/10 * * * *'  # a cada 10 minutos
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Baixar arquivo epg.xml do repositório externo
        run: |
          curl -L -o epg.xml "https://raw.githubusercontent.com/limaalef/BrazilTVEPG/refs/heads/main/epg.xml"

      - name: Commit e push (se houver mudanças)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add epg.xml
          if git diff --cached --quiet; then
            echo "Nenhuma mudança detectada"
          else
            git commit -m "Atualização automática do EPG via repositório limaalef"
            git push
          fi
